Pinnacle/config/routes.rb
Pinnacle::Application.routes.draw do
  resources :periods

  resources :participants

  resources :events

  get "pin_fees/read_feed"

  post "pin_fees/read_feed" => "pin_fees#start_feed"

  get "pin_fees/start_feed"

  get "pin_fees/no_feed"

  get "pin_fees/save_feeder"

  post "pin_fees/save_feeder"

  resources :pinnacle_feeds

end

Pinnacle/app/models/pinnacle_feed.rb
class PinnacleFeed < ActiveRecord::Base
  attr_accessible :last_contest, :last_game, :pinnacle_feed_time, :sport_sub_type, :sport_type

  require 'open-uri'

  pinnacle_feed_link = "http://xml.pinnaclesports.com/pinnacleFeed.aspx"

  def read_feed (sport_type, sport_sub_type, last)
    expand_uri = '?'
    expand_uri_joiner = ''
    if sport_type != nil
      expand_uri.concat("SportType=").concat(sport_type)
      expand_uri_joiner = '&'
    end
    if sport_sub_type != nil
      expand_uri.concat(expand_uri_joiner).concat("SportSubType=").concat(sport_sub_type)
      expand_uri_joiner = '&'
    end
    if last != nil
      expand_uri.concat(expand_uri_joiner).concat("last=").concat(last)
    end

    reponse = open(pinnacle_feed_link.concat(expand_uri)).read

    return response

  end


end

Pinnacle/app/controllers/pinnacle_feeds_controller.rb
class PinnacleFeedsController < ApplicationController
  # GET /pinnacle_feeds
  # GET /pinnacle_feeds.json
  def index
    #@pinnacle_feeds = PinnacleFeed.all.reverse
    @pinnacle_feeds = PinnacleFeed.where(['created_at >= ?',  Date.today-3] ).reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pinnacle_feeds }
    end
  end

  # GET /pinnacle_feeds/1
  # GET /pinnacle_feeds/1.json
  def show
    @pinnacle_feed = PinnacleFeed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pinnacle_feed }
    end
  end

  # GET /pinnacle_feeds/new
  # GET /pinnacle_feeds/new.json
  def new
    @pinnacle_feed = PinnacleFeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pinnacle_feed }
    end
  end

  # GET /pinnacle_feeds/1/edit
  def edit
    @pinnacle_feed = PinnacleFeed.find(params[:id])
  end

  # POST /pinnacle_feeds
  # POST /pinnacle_feeds.json
  def create
    @pinnacle_feed = PinnacleFeed.new(params[:pinnacle_feed])

    respond_to do |format|
      if @pinnacle_feed.save
        format.html { redirect_to @pinnacle_feed, notice: 'Pinnacle feed was successfully created.' }
        format.json { render json: @pinnacle_feed, status: :created, location: @pinnacle_feed }
      else
        format.html { render action: "new" }
        format.json { render json: @pinnacle_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pinnacle_feeds/1
  # PUT /pinnacle_feeds/1.json
  def update
    @pinnacle_feed = PinnacleFeed.find(params[:id])

    respond_to do |format|
      if @pinnacle_feed.update_attributes(params[:pinnacle_feed])
        format.html { redirect_to @pinnacle_feed, notice: 'Pinnacle feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pinnacle_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pinnacle_feeds/1
  # DELETE /pinnacle_feeds/1.json
  def destroy
    @pinnacle_feed = PinnacleFeed.find(params[:id])
    @pinnacle_feed.destroy

    respond_to do |format|
      format.html { redirect_to pinnacle_feeds_url }
      format.json { head :no_content }
    end
  end
end

Pinnacle/app/helpers/pinnacle_feeds_helper.rb
module PinnacleFeedsHelper
end

Pinnacle/app/views/pinnacle_feeds/_form.html.erb
<%= form_for(@pinnacle_feed) do |f| %>
  <% if @pinnacle_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pinnacle_feed.errors.count, "error") %> prohibited this pinnacle_feed from being saved:</h2>

      <ul>
      <% @pinnacle_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pinnacle_feed_time %><br />
    <%= f.number_field :pinnacle_feed_time %>
  </div>
  <div class="field">
    <%= f.label :last_contest %><br />
    <%= f.number_field :last_contest %>
  </div>
  <div class="field">
    <%= f.label :last_game %><br />
    <%= f.number_field :last_game %>
  </div>
  <div class="field">
    <%= f.label :sport_type %><br />
    <%= f.text_field :sport_type %>
  </div>
  <div class="field">
    <%= f.label :sport_sub_type %><br />
    <%= f.text_field :sport_sub_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pinnacle/app/views/pinnacle_feeds/edit.html.erb
<h1>Editing pinnacle_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @pinnacle_feed %> |
<%= link_to 'Back', pinnacle_feeds_path %>

Pinnacle/app/views/pinnacle_feeds/index.html.erb
<h1>Listing pinnacle_feeds</h1>

<table>
  <tr>
    <th>Pinnacle feed time</th>
    <th>Last contest</th>
    <th>Last game</th>
    <th>Sport type</th>
    <th>Sport sub type</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pinnacle_feeds.each do |pinnacle_feed| %>
  <tr>
    <td><%= pinnacle_feed.pinnacle_feed_time %></td>
    <td><%= pinnacle_feed.last_contest %></td>
    <td><%= pinnacle_feed.last_game %></td>
    <td><%= pinnacle_feed.sport_type %></td>
    <td><%= pinnacle_feed.sport_sub_type %></td>
    <td><%= pinnacle_feed.created_at %></td>
    <td><%= link_to 'Show', pinnacle_feed %></td>
    <td><%= link_to 'Edit', edit_pinnacle_feed_path(pinnacle_feed) %></td>
    <td><%= link_to 'Destroy', pinnacle_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pinnacle feed', new_pinnacle_feed_path %>

Pinnacle/app/views/pinnacle_feeds/new.html.erb
<h1>New pinnacle_feed</h1>

<%= render 'form' %>

<%= link_to 'Back', pinnacle_feeds_path %>

Pinnacle/app/views/pinnacle_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pinnacle feed time:</b>
  <%= @pinnacle_feed.pinnacle_feed_time %>
</p>

<p>
  <b>Last contest:</b>
  <%= @pinnacle_feed.last_contest %>
</p>

<p>
  <b>Last game:</b>
  <%= @pinnacle_feed.last_game %>
</p>

<p>
  <b>Sport type:</b>
  <%= @pinnacle_feed.sport_type %>
</p>

<p>
  <b>Sport sub type:</b>
  <%= @pinnacle_feed.sport_sub_type %>
</p>


<%= link_to 'Edit', edit_pinnacle_feed_path(@pinnacle_feed) %> |
<%= link_to 'Back', pinnacle_feeds_path %>