Pinnacle/config/routes.rb
Pinnacle::Application.routes.draw do
  resources :periods

  resources :participants

  resources :events

  get "pin_fees/read_feed"

  post "pin_fees/read_feed" => "pin_fees#start_feed"

  get "pin_fees/start_feed"

  get "pin_fees/no_feed"

  get "pin_fees/save_feeder"

  post "pin_fees/save_feeder"

  resources :pinnacle_feeds

end

Pinnacle/app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :contestantnum, :event_game_number, :participant_name, :rotnum, :visiting_home_draw
  belongs_to :event
end

Pinnacle/app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

Pinnacle/app/helpers/participants_helper.rb
module ParticipantsHelper
end

Pinnacle/app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :participant_name %><br />
    <%= f.text_field :participant_name %>
  </div>
  <div class="field">
    <%= f.label :contestantnum %><br />
    <%= f.number_field :contestantnum %>
  </div>
  <div class="field">
    <%= f.label :rotnum %><br />
    <%= f.number_field :rotnum %>
  </div>
  <div class="field">
    <%= f.label :visiting_home_draw %><br />
    <%= f.text_field :visiting_home_draw %>
  </div>
  <div class="field">
    <%= f.label :event_game_number %><br />
    <%= f.number_field :event_game_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pinnacle/app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

Pinnacle/app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Participant name</th>
    <th>Contestantnum</th>
    <th>Rotnum</th>
    <th>Visiting home draw</th>
    <th>Event gamenumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.participant_name %></td>
    <td><%= participant.contestantnum %></td>
    <td><%= participant.rotnum %></td>
    <td><%= participant.visiting_home_draw %></td>
    <td><%= participant.event_game_number %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

Pinnacle/app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

Pinnacle/app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Participant name:</b>
  <%= @participant.participant_name %>
</p>

<p>
  <b>Contestantnum:</b>
  <%= @participant.contestantnum %>
</p>

<p>
  <b>Rotnum:</b>
  <%= @participant.rotnum %>
</p>

<p>
  <b>Visiting home draw:</b>
  <%= @participant.visiting_home_draw %>
</p>

<p>
  <b>Event game number:</b>
  <%= @participant.event_game_number %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>