Pinnacle/config/routes.rb
Pinnacle::Application.routes.draw do
  resources :periods

  resources :participants

  resources :events

  get "pin_fees/read_feed"

  post "pin_fees/read_feed" => "pin_fees#start_feed"

  get "pin_fees/start_feed"

  get "pin_fees/no_feed"

  get "pin_fees/save_feeder"

  post "pin_fees/save_feeder"

  resources :pinnacle_feeds

end

Pinnacle/app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :event_game_number, :moneyline_maximum, :period_cutoff_datetimeGMT, :period_description, :period_number, :period_status, :period_update, :spread_maximum, :total_maximum
  belongs_to :event
end

Pinnacle/app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
    @period = Period.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/new
  # GET /periods/new.json
  def new
    @period = Period.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/1/edit
  def edit
    @period = Period.find(params[:id])
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(params[:period])

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render json: @period, status: :created, location: @period }
      else
        format.html { render action: "new" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /periods/1
  # PUT /periods/1.json
  def update
    @period = Period.find(params[:id])

    respond_to do |format|
      if @period.update_attributes(params[:period])
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period = Period.find(params[:id])
    @period.destroy

    respond_to do |format|
      format.html { redirect_to periods_url }
      format.json { head :no_content }
    end
  end
end

Pinnacle/app/helpers/periods_helper.rb
module PeriodsHelper
end

Pinnacle/app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :event_game_number %><br />
    <%= f.number_field :event_game_number %>
  </div>

  <div class="field">
    <%= f.label :period_number %><br />
    <%= f.number_field :period_number %>
  </div>
  <div class="field">
    <%= f.label :period_description %><br />
    <%= f.text_field :period_description %>
  </div>
  <div class="field">
    <%= f.label :period_cutoff_datetimeGMT %><br />
    <%= f.datetime_select :period_cutoff_datetimeGMT %>
  </div>
  <div class="field">
    <%= f.label :period_status %><br />
    <%= f.text_field :period_status %>
  </div>
  <div class="field">
    <%= f.label :period_update %><br />
    <%= f.text_field :period_update %>
  </div>
  <div class="field">
    <%= f.label :spread_maximum %><br />
    <%= f.text_field :spread_maximum %>
  </div>
  <div class="field">
    <%= f.label :moneyline_maximum %><br />
    <%= f.text_field :moneyline_maximum %>
  </div>
  <div class="field">
    <%= f.label :total_maximum %><br />
    <%= f.text_field :total_maximum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pinnacle/app/views/periods/edit.html.erb
<h1>Editing period</h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

Pinnacle/app/views/periods/index.html.erb
<h1>Listing periods</h1>

<table>
  <tr>
    <th>Event game number</th>
    <th>Period number</th>
    <th>Period description</th>
    <th>Period cutoff datetimegmt</th>
    <th>Period status</th>
    <th>Period update</th>
    <th>Spread maximum</th>
    <th>Moneyline maximum</th>
    <th>Total maximum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @periods.each do |period| %>
  <tr>
    <td><%= period.event_game_number %></td>
    <td><%= period.period_number %></td>
    <td><%= period.period_description %></td>
    <td><%= period.period_cutoff_datetimeGMT %></td>
    <td><%= period.period_status %></td>
    <td><%= period.period_update %></td>
    <td><%= period.spread_maximum %></td>
    <td><%= period.moneyline_maximum %></td>
    <td><%= period.total_maximum %></td>
    <td><%= link_to 'Show', period %></td>
    <td><%= link_to 'Edit', edit_period_path(period) %></td>
    <td><%= link_to 'Destroy', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Period', new_period_path %>

Pinnacle/app/views/periods/new.html.erb
<h1>New period</h1>

<%= render 'form' %>

<%= link_to 'Back', periods_path %>

Pinnacle/app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Event game number:</b>
  <%= @period.event_game_number %>
</p>


<p>
  <b>Period number:</b>
  <%= @period.period_number %>
</p>

<p>
  <b>Period description:</b>
  <%= @period.period_description %>
</p>

<p>
  <b>Period cutoff datetimegmt:</b>
  <%= @period.period_cutoff_datetimeGMT %>
</p>

<p>
  <b>Period status:</b>
  <%= @period.period_status %>
</p>

<p>
  <b>Period update:</b>
  <%= @period.period_update %>
</p>

<p>
  <b>Spread maximum:</b>
  <%= @period.spread_maximum %>
</p>

<p>
  <b>Moneyline maximum:</b>
  <%= @period.moneyline_maximum %>
</p>

<p>
  <b>Total maximum:</b>
  <%= @period.total_maximum %>
</p>


<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>